spring:
  application.name: matches-dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${sm://matches_database_url}
    username: ${sm://matches_database_user}
    password: ${sm://matches_database_password}
  flyway:
    enabled: false
    url: ${sm://matches_database_url}
    user: ${sm://matches_database_user}
    password: ${sm://matches_database_password}

  rabbitmq:
      addresses: ${sm://lostcities_event_queue_url}
      port: 1883

  cloud:
    consul.enabled: false

server:
  port: 8091

logging:
  level:
    ROOT: error
    io.dereknelson.lostcities: debug
    org.springframework.security.web.FilterChainProxy: error
    org.springframework.amqp.rabbit.connection: error
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: '%d{"yyyy-MM-dd''T''HH:mm:ss,SSS"} application=${spring.application.name} profiles=${spring.profiles.active} %-5level [%thread] %logger : %msg%n'
    dateformat: yyyy-MM-dd'T'HH:mm:ssxxx
  file:
    name: /root/Logs/${spring.application.name}-stage.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
