spring:
  application.name: matches-dev
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  jackson.serialization.indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.20.0.25:5432/lostcities-matches
    username: matches
    password: example
  flyway:
    enabled: false
    url: jdbc:postgresql://172.20.0.25:5432/lostcities-matches
    user: matches
    password: example

  rabbitmq:
    addresses: 172.20.0.60
    port: 5672
    username: guest
    password: guest
