INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ANONYMOUS');

INSERT INTO PUBLIC.USER (ID, EMAIL, LOGIN, PASSWORD_HASH, FIRST_NAME, LAST_NAME, IMAGE_URL, LANG_KEY, ACTIVATED, ACTIVATION_KEY, RESET_DATE, RESET_KEY, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE) VALUES (1, 'test@example.com', 'ttesterson', '$2a$10$D.Dw85INzMCMAp5F3Oce4OTm5z47DG6AR7DmX0T5rIrRoDg/c/80e', 'Test', 'Testerson', null, 'en_US', true, null, null, null, 'anonymousUser', '2021-05-13 17:53:31.417621', 'anonymousUser', '2021-05-13 17:53:31.417621');
INSERT INTO PUBLIC.USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
