INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ANONYMOUS');

INSERT INTO USER
    (ID, EMAIL, LOGIN, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, ACTIVATED, ACTIVATION_KEY, FIRST_NAME, IMAGE_URL, LANG_KEY, LAST_NAME, PASSWORD_HASH, RESET_DATE, RESET_KEY)
VALUES
    (1, 'contact@dereknelson.io', 'dnelson', 'anonymousUser', '2021-05-02 18:43:03.976513', 'anonymousUser', '2021-05-02 18:43:03.976513', false, null, 'Derek', null, 'en_US', 'Nelson', 'testing', null, null);

INSERT INTO USER
    (ID, EMAIL, LOGIN, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, ACTIVATED, ACTIVATION_KEY, FIRST_NAME, IMAGE_URL, LANG_KEY, LAST_NAME, PASSWORD_HASH, RESET_DATE, RESET_KEY)
VALUES
    (2, 'ttesterson@example.com', 'ttesterson', 'anonymousUser', '2021-05-02 18:44:19.288534', 'anonymousUser', '2021-05-02 18:44:19.288534', false, null, 'Test', null, 'en_US', 'Testerson', 'testing', null, null);

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) VALUES (2, 'ROLE_USER');
